### PR TITLE
Upgrade Ember

### PR DESCRIPTION
**Pull request by Robdel12**
## What is this?

This PR upgrades this project to the most up to date version of Ember (3.4). I also switched this project over to the new angle bracket components. 

## TODOs

- [x] Hook CI up to this rep?

### CODE REVIEW

**Comment by Robdel12** [comment]
Looks like I'm a member and can merge now. Can I get a review?

**Comment by cadeParade** [comment]
Sorry, I just got the email about this now. 
What QA steps have you taken?

**Comment by Robdel12** [comment]
@cadeParade This was basically the base of my interview project (which I pulled from https://github.com/Robdel12/ember-todomvc to here). All of the tests pass (a long with the percy visual tests). I see the hooking the repo up to CI todo I left is checked. Do we hook CI up to the other example projects?

**Comment by Robdel12** [comment]
I've added the proper CI config, & the tests pass for me locally. Since this started as a fork I'm going to merge this PR and if there's any needed debugging I'll get that in a follow up PR 😃

**Pull request merged**
